name: deploy

on:
  pull_request:
    branches:
      - develop

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out a repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Using Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Installing node modules
        run: npm install
      - name: Running unit tests
        run: npm test
