name: deploy

on:
  push:
    branches:
      - develop

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out a repository
        uses: actions/checkout@v2
      - name: Using Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Installing node modules
        run: npm install
      - name: Preparing the app build
        run: npm run build --if-present
      - name: Signing up to Heroku using credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Adding Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ci-cd-react-test-app-staging
      - name: Renaming the Heroku remote
        run: git remote rename heroku heroku-staging
      - name: Merging the main to the develop
        run: |
          git fetch
          echo $(git branch -a)
          git merge heroku-staging main
      - name: Pushing to Heroku
        run: git push heroku-staging develop:main
